---
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/acc"
  mode: "max"
  save_top_k: 3
  save_last: True
  verbose: False
  dirpath: "checkpoints/"
  filename: "DeepMoon-epoch_{epoch:03d}"
  auto_insert_metric_name: False

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/acc"
  mode: "max"
  patience: 100
  min_delta: 0

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: -1

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar