# @package _global_

hydra:
  run:
    dir: ${log_dir_path}/logs/evaluations/runs/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${log_dir_path}/logs/evaluations/multiruns/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}