# @package _global_
defaults:
  - override /log_dir: debug.yaml

trainer:
  max_epochs: 1
  gpus: 0
  detect_anomaly: true
  track_grad_norm: 2

datamodule:
  num_workers: 0
  pin_memory: False

hydra:
  verbose: True

print_config: False